//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 04:44:04 PM EAT 
//


package com.example.demo.object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for a2ACreditDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="a2ACreditDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ws.webgate.bpc.ru/}a2ARequestDTO"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="amount" type="{http://ws.webgate.bpc.ru/}amountDTO"/&gt;
 *         &lt;element name="origRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "a2ACreditDTO", propOrder = {
    "amount",
    "origRefNum"
})
public class A2ACreditDTO
    extends A2ARequestDTO
{

    @XmlElement(required = true)
    protected AmountDTO amount;
    protected String origRefNum;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountDTO }
     *     
     */
    public AmountDTO getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountDTO }
     *     
     */
    public void setAmount(AmountDTO value) {
        this.amount = value;
    }

    /**
     * Gets the value of the origRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigRefNum() {
        return origRefNum;
    }

    /**
     * Sets the value of the origRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigRefNum(String value) {
        this.origRefNum = value;
    }

}
