//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 04:44:04 PM EAT 
//


package com.example.demo.object;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for a2aEnquiryResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="a2aEnquiryResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reply" type="{http://ws.webgate.bpc.ru/}a2AEnquiryReplyDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "a2aEnquiryResponse", propOrder = {
        "reply"
})
@XmlRootElement(name = "a2aEnquiryResponse", namespace = "http://ws.webgate.bpc.ru/")
public class A2AEnquiryResponse {

    @XmlElement(required = true)
    protected A2AEnquiryReplyDTO reply;

    /**
     * Gets the value of the reply property.
     *
     * @return possible object is
     * {@link A2AEnquiryReplyDTO }
     */
    public A2AEnquiryReplyDTO getReply() {
        return reply;
    }

    /**
     * Sets the value of the reply property.
     *
     * @param value allowed object is
     *              {@link A2AEnquiryReplyDTO }
     */
    public void setReply(A2AEnquiryReplyDTO value) {
        this.reply = value;
    }

}
