//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 04:44:04 PM EAT 
//


package com.example.demo.object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for a2aGetTransStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="a2aGetTransStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="a2aGetTransStatus" type="{http://ws.webgate.bpc.ru/}a2AGetTransStatusDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "a2aGetTransStatus", propOrder = {
    "a2AGetTransStatus"
})
public class A2AGetTransStatus {

    @XmlElement(name = "a2aGetTransStatus", required = true)
    protected A2AGetTransStatusDTO a2AGetTransStatus;

    /**
     * Gets the value of the a2AGetTransStatus property.
     * 
     * @return
     *     possible object is
     *     {@link A2AGetTransStatusDTO }
     *     
     */
    public A2AGetTransStatusDTO getA2AGetTransStatus() {
        return a2AGetTransStatus;
    }

    /**
     * Sets the value of the a2AGetTransStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link A2AGetTransStatusDTO }
     *     
     */
    public void setA2AGetTransStatus(A2AGetTransStatusDTO value) {
        this.a2AGetTransStatus = value;
    }

}
