//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 04:44:04 PM EAT 
//


package com.example.demo.object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for a2ARequestDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="a2ARequestDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="destAccount" type="{http://ws.webgate.bpc.ru/}accountDetailsDTO"/&gt;
 *         &lt;element name="acqTerminalDetails" type="{http://ws.webgate.bpc.ru/}terminalDetailsDTO"/&gt;
 *         &lt;element name="sourceBin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="refNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="localTransactionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="sttlDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "a2ARequestDTO", propOrder = {
    "destAccount",
    "acqTerminalDetails",
    "sourceBin",
    "refNum",
    "message",
    "localTransactionDateTime",
    "sttlDate"
})
@XmlSeeAlso({
    A2ACreditDTO.class,
    A2AEnquiryDTO.class
})
public class A2ARequestDTO {

    @XmlElement(required = true)
    protected AccountDetailsDTO destAccount;
    @XmlElement(required = true)
    protected TerminalDetailsDTO acqTerminalDetails;
    @XmlElement(required = true)
    protected String sourceBin;
    @XmlElement(required = true)
    protected String refNum;
    protected String message;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar localTransactionDateTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sttlDate;

    /**
     * Gets the value of the destAccount property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetailsDTO }
     *     
     */
    public AccountDetailsDTO getDestAccount() {
        return destAccount;
    }

    /**
     * Sets the value of the destAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetailsDTO }
     *     
     */
    public void setDestAccount(AccountDetailsDTO value) {
        this.destAccount = value;
    }

    /**
     * Gets the value of the acqTerminalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TerminalDetailsDTO }
     *     
     */
    public TerminalDetailsDTO getAcqTerminalDetails() {
        return acqTerminalDetails;
    }

    /**
     * Sets the value of the acqTerminalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminalDetailsDTO }
     *     
     */
    public void setAcqTerminalDetails(TerminalDetailsDTO value) {
        this.acqTerminalDetails = value;
    }

    /**
     * Gets the value of the sourceBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBin() {
        return sourceBin;
    }

    /**
     * Sets the value of the sourceBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBin(String value) {
        this.sourceBin = value;
    }

    /**
     * Gets the value of the refNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNum() {
        return refNum;
    }

    /**
     * Sets the value of the refNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNum(String value) {
        this.refNum = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the localTransactionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLocalTransactionDateTime() {
        return localTransactionDateTime;
    }

    /**
     * Sets the value of the localTransactionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLocalTransactionDateTime(XMLGregorianCalendar value) {
        this.localTransactionDateTime = value;
    }

    /**
     * Gets the value of the sttlDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSttlDate() {
        return sttlDate;
    }

    /**
     * Sets the value of the sttlDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSttlDate(XMLGregorianCalendar value) {
        this.sttlDate = value;
    }

}
