//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.21 at 04:44:04 PM EAT 
//


package com.example.demo.object;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.bpc.webgate.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _COMMAND_QNAME = new QName("http://ws.webgate.bpc.ru/", "COMMAND");
    private final static QName _A2ACreditDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2ACreditDTO");
    private final static QName _A2ACreditReplyDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2ACreditReplyDTO");
    private final static QName _A2AEnquiryDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2AEnquiryDTO");
    private final static QName _A2AEnquiryReplyDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2AEnquiryReplyDTO");
    private final static QName _A2AGetTransStatusDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2AGetTransStatusDTO");
    private final static QName _A2AGetTransStatusReplyDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2AGetTransStatusReplyDTO");
    private final static QName _A2AReplyDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2AReplyDTO");
    private final static QName _A2ARequestDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2ARequestDTO");
    private final static QName _A2ACredit_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aCredit");
    private final static QName _A2ACreditResponse_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aCreditResponse");
    private final static QName _A2AEnquiry_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aEnquiry");
    private final static QName _A2AEnquiryResponse_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aEnquiryResponse");
    private final static QName _A2AGetTransStatus_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aGetTransStatus");
    private final static QName _A2AGetTransStatusResponse_QNAME = new QName("http://ws.webgate.bpc.ru/", "a2aGetTransStatusResponse");
    private final static QName _AccountDetailsDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "accountDetailsDTO");
    private final static QName _AmountDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "amountDTO");
    private final static QName _Credentials_QNAME = new QName("http://ws.webgate.bpc.ru/", "credentials");
    private final static QName _ReplyDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "replyDTO");
    private final static QName _TerminalDetailsDTO_QNAME = new QName("http://ws.webgate.bpc.ru/", "terminalDetailsDTO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.bpc.webgate.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link A2ACreditDTO }
     * 
     */
    public A2ACreditDTO createA2ACreditDTO() {
        return new A2ACreditDTO();
    }

    /**
     * Create an instance of {@link A2ACreditReplyDTO }
     * 
     */
    public A2ACreditReplyDTO createA2ACreditReplyDTO() {
        return new A2ACreditReplyDTO();
    }

    /**
     * Create an instance of {@link A2AEnquiryDTO }
     * 
     */
    public A2AEnquiryDTO createA2AEnquiryDTO() {
        return new A2AEnquiryDTO();
    }

    /**
     * Create an instance of {@link A2AEnquiryReplyDTO }
     * 
     */
    public A2AEnquiryReplyDTO createA2AEnquiryReplyDTO() {
        return new A2AEnquiryReplyDTO();
    }

    /**
     * Create an instance of {@link A2AGetTransStatusDTO }
     * 
     */
    public A2AGetTransStatusDTO createA2AGetTransStatusDTO() {
        return new A2AGetTransStatusDTO();
    }

    /**
     * Create an instance of {@link A2AGetTransStatusReplyDTO }
     * 
     */
    public A2AGetTransStatusReplyDTO createA2AGetTransStatusReplyDTO() {
        return new A2AGetTransStatusReplyDTO();
    }

    /**
     * Create an instance of {@link A2AReplyDTO }
     * 
     */
    public A2AReplyDTO createA2AReplyDTO() {
        return new A2AReplyDTO();
    }

    /**
     * Create an instance of {@link A2ARequestDTO }
     * 
     */
    public A2ARequestDTO createA2ARequestDTO() {
        return new A2ARequestDTO();
    }

    /**
     * Create an instance of {@link A2ACredit }
     * 
     */
    public A2ACredit createA2ACredit() {
        return new A2ACredit();
    }

    /**
     * Create an instance of {@link A2ACreditResponse }
     * 
     */
    public A2ACreditResponse createA2ACreditResponse() {
        return new A2ACreditResponse();
    }

    /**
     * Create an instance of {@link A2AEnquiry }
     * 
     */
    public A2AEnquiry createA2AEnquiry() {
        return new A2AEnquiry();
    }

    /**
     * Create an instance of {@link A2AEnquiryResponse }
     * 
     */
    public A2AEnquiryResponse createA2AEnquiryResponse() {
        return new A2AEnquiryResponse();
    }

    /**
     * Create an instance of {@link A2AGetTransStatus }
     * 
     */
    public A2AGetTransStatus createA2AGetTransStatus() {
        return new A2AGetTransStatus();
    }

    /**
     * Create an instance of {@link A2AGetTransStatusResponse }
     * 
     */
    public A2AGetTransStatusResponse createA2AGetTransStatusResponse() {
        return new A2AGetTransStatusResponse();
    }

    /**
     * Create an instance of {@link AccountDetailsDTO }
     * 
     */
    public AccountDetailsDTO createAccountDetailsDTO() {
        return new AccountDetailsDTO();
    }

    /**
     * Create an instance of {@link AmountDTO }
     * 
     */
    public AmountDTO createAmountDTO() {
        return new AmountDTO();
    }

    /**
     * Create an instance of {@link CredentialsDTO }
     * 
     */
    public CredentialsDTO createCredentialsDTO() {
        return new CredentialsDTO();
    }

    /**
     * Create an instance of {@link ReplyDTO }
     * 
     */
    public ReplyDTO createReplyDTO() {
        return new ReplyDTO();
    }

    /**
     * Create an instance of {@link TerminalDetailsDTO }
     * 
     */
    public TerminalDetailsDTO createTerminalDetailsDTO() {
        return new TerminalDetailsDTO();
    }

    /**
     * Create an instance of {@link AirtelTopup }
     * 
     */
    public AirtelTopup createAirtelTopup() {
        return new AirtelTopup();
    }

    /**
     * Create an instance of {@link AirtelTopupResponse }
     * 
     */
    public AirtelTopupResponse createAirtelTopupResponse() {
        return new AirtelTopupResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "COMMAND")
    public JAXBElement<Object> createCOMMAND(Object value) {
        return new JAXBElement<Object>(_COMMAND_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2ACreditDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2ACreditDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2ACreditDTO")
    public JAXBElement<A2ACreditDTO> createA2ACreditDTO(A2ACreditDTO value) {
        return new JAXBElement<A2ACreditDTO>(_A2ACreditDTO_QNAME, A2ACreditDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2ACreditReplyDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2ACreditReplyDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2ACreditReplyDTO")
    public JAXBElement<A2ACreditReplyDTO> createA2ACreditReplyDTO(A2ACreditReplyDTO value) {
        return new JAXBElement<A2ACreditReplyDTO>(_A2ACreditReplyDTO_QNAME, A2ACreditReplyDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AEnquiryDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AEnquiryDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2AEnquiryDTO")
    public JAXBElement<A2AEnquiryDTO> createA2AEnquiryDTO(A2AEnquiryDTO value) {
        return new JAXBElement<A2AEnquiryDTO>(_A2AEnquiryDTO_QNAME, A2AEnquiryDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AEnquiryReplyDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AEnquiryReplyDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2AEnquiryReplyDTO")
    public JAXBElement<A2AEnquiryReplyDTO> createA2AEnquiryReplyDTO(A2AEnquiryReplyDTO value) {
        return new JAXBElement<A2AEnquiryReplyDTO>(_A2AEnquiryReplyDTO_QNAME, A2AEnquiryReplyDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2AGetTransStatusDTO")
    public JAXBElement<A2AGetTransStatusDTO> createA2AGetTransStatusDTO(A2AGetTransStatusDTO value) {
        return new JAXBElement<A2AGetTransStatusDTO>(_A2AGetTransStatusDTO_QNAME, A2AGetTransStatusDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusReplyDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusReplyDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2AGetTransStatusReplyDTO")
    public JAXBElement<A2AGetTransStatusReplyDTO> createA2AGetTransStatusReplyDTO(A2AGetTransStatusReplyDTO value) {
        return new JAXBElement<A2AGetTransStatusReplyDTO>(_A2AGetTransStatusReplyDTO_QNAME, A2AGetTransStatusReplyDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AReplyDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AReplyDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2AReplyDTO")
    public JAXBElement<A2AReplyDTO> createA2AReplyDTO(A2AReplyDTO value) {
        return new JAXBElement<A2AReplyDTO>(_A2AReplyDTO_QNAME, A2AReplyDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2ARequestDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2ARequestDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2ARequestDTO")
    public JAXBElement<A2ARequestDTO> createA2ARequestDTO(A2ARequestDTO value) {
        return new JAXBElement<A2ARequestDTO>(_A2ARequestDTO_QNAME, A2ARequestDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2ACredit }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2ACredit }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aCredit")
    public JAXBElement<A2ACredit> createA2ACredit(A2ACredit value) {
        return new JAXBElement<A2ACredit>(_A2ACredit_QNAME, A2ACredit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2ACreditResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2ACreditResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aCreditResponse")
    public JAXBElement<A2ACreditResponse> createA2ACreditResponse(A2ACreditResponse value) {
        return new JAXBElement<A2ACreditResponse>(_A2ACreditResponse_QNAME, A2ACreditResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AEnquiry }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AEnquiry }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aEnquiry")
    public JAXBElement<A2AEnquiry> createA2AEnquiry(A2AEnquiry value) {
        return new JAXBElement<A2AEnquiry>(_A2AEnquiry_QNAME, A2AEnquiry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AEnquiryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AEnquiryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aEnquiryResponse")
    public JAXBElement<A2AEnquiryResponse> createA2AEnquiryResponse(A2AEnquiryResponse value) {
        return new JAXBElement<A2AEnquiryResponse>(_A2AEnquiryResponse_QNAME, A2AEnquiryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aGetTransStatus")
    public JAXBElement<A2AGetTransStatus> createA2AGetTransStatus(A2AGetTransStatus value) {
        return new JAXBElement<A2AGetTransStatus>(_A2AGetTransStatus_QNAME, A2AGetTransStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link A2AGetTransStatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "a2aGetTransStatusResponse")
    public JAXBElement<A2AGetTransStatusResponse> createA2AGetTransStatusResponse(A2AGetTransStatusResponse value) {
        return new JAXBElement<A2AGetTransStatusResponse>(_A2AGetTransStatusResponse_QNAME, A2AGetTransStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountDetailsDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountDetailsDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "accountDetailsDTO")
    public JAXBElement<AccountDetailsDTO> createAccountDetailsDTO(AccountDetailsDTO value) {
        return new JAXBElement<AccountDetailsDTO>(_AccountDetailsDTO_QNAME, AccountDetailsDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AmountDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "amountDTO")
    public JAXBElement<AmountDTO> createAmountDTO(AmountDTO value) {
        return new JAXBElement<AmountDTO>(_AmountDTO_QNAME, AmountDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialsDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CredentialsDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "credentials")
    public JAXBElement<CredentialsDTO> createCredentials(CredentialsDTO value) {
        return new JAXBElement<CredentialsDTO>(_Credentials_QNAME, CredentialsDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplyDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReplyDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "replyDTO")
    public JAXBElement<ReplyDTO> createReplyDTO(ReplyDTO value) {
        return new JAXBElement<ReplyDTO>(_ReplyDTO_QNAME, ReplyDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminalDetailsDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TerminalDetailsDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.webgate.bpc.ru/", name = "terminalDetailsDTO")
    public JAXBElement<TerminalDetailsDTO> createTerminalDetailsDTO(TerminalDetailsDTO value) {
        return new JAXBElement<TerminalDetailsDTO>(_TerminalDetailsDTO_QNAME, TerminalDetailsDTO.class, null, value);
    }

}
